#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 StackBlender LLC
#
# Assembles the SPC700 boot ROM (64 bytes at $FFC0-$FFFF) from the program below and writes
# spc700-boot-rom.bin, spc700_boot_rom.h and listing.txt (python3 src/assemble.py [DIR],
# default: the repository's root). Written from public descriptions of the boot protocol
# only (docs/protocol.md), never from the original ROM.

ORG = 0xFFC0

# (label or None, bytes, comment); branch operands are ("rel", label).
program = [
    ("reset", [0xCD, 0xEF], "mov x,#$ef"),
    (None, [0xBD], "mov sp,x            ; stack at $01EF"),
    (None, [0xE8, 0x00], "mov a,#0"),
    ("clear", [0xC6], "mov (x),a           ; clear $EF..$01"),
    (None, [0x1D], "dec x"),
    (None, [0xD0, ("rel", "clear")], "bne clear"),
    (None, [0xC6], "mov (x),a           ; and $00 (x is 0 from here on)"),
    (None, [0x8F, 0xAA, 0xF4], "mov $f4,#$aa        ; ready: $AA $BB"),
    (None, [0x8F, 0xBB, 0xF5], "mov $f5,#$bb"),
    ("kick", [0x78, 0xCC, 0xF4], "cmp $f4,#$cc        ; wait for the CPU's $CC"),
    (None, [0xD0, ("rel", "kick")], "bne kick"),
    # A command: ports 2-3 the address, port 1 zero to jump there or nonzero for a
    # block to it, port 0 the command's value (written last), echoed.
    ("command", [0xBA, 0xF6], "movw ya,$f6         ; the address"),
    (None, [0xDA, 0x00], "movw $00,ya         ; kept at $00-$01"),
    (None, [0xFA, 0xF4, 0xF4], "mov $f4,$f4         ; echo the command"),
    (None, [0xE4, 0xF5], "mov a,$f5"),
    (None, [0xF0, ("rel", "jump")], "beq jump"),
    (None, [0x8D, 0x00], "mov y,#0            ; counter and index"),
    ("first", [0x7E, 0xF4], "cmp y,$f4           ; wait for the first byte's counter (0)"),
    (None, [0xD0, ("rel", "first")], "bne first"),
    # The time from the CPU writing a counter to our echo, and from the echo back to
    # watching for the next, set the transfer's speed (games time their uploads by the
    # console's): the common case takes no branch it can avoid.
    ("data", [0xE4, 0xF5], "mov a,$f5           ; a byte"),
    (None, [0xCB, 0xF4], "mov $f4,y           ; echo its counter (the CPU sends the next while it's stored)"),
    (None, [0xD7, 0x00], "mov [$00]+y,a"),
    (None, [0xFC], "inc y"),
    (None, [0xF0, ("rel", "page")], "beq page            ; every 256 bytes"),
    ("next", [0x7E, 0xF4], "cmp y,$f4           ; the next counter?"),
    (None, [0xF0, ("rel", "data")], "beq data"),
    (None, [0x10, ("rel", "next")], "bpl next            ; not yet (the CPU still shows the last one)"),
    (None, [0x2F, ("rel", "command")], "bra command         ; ahead of it: the block's end, a command"),
    ("page", [0xAB, 0x01], "inc $01             ; the next 256-byte page"),
    (None, [0x2F, ("rel", "next")], "bra next"),
    ("jump", [0x1F, 0x00, 0x00], "jmp [$0000+x]       ; to the address at $00-$01"),
]

# Pass 1: addresses.
labels, address = {}, ORG
for label, code, _ in program:
    if label:
        labels[label] = address
    address += len(code)
end = address
assert end <= 0xFFFE, f"program too long: ends at ${end:04X}"

# Pass 2: bytes.
out, address = [], ORG
lines = []
for label, code, comment in program:
    start = address
    encoded = []
    for i, b in enumerate(code):
        if isinstance(b, tuple):
            target = labels[b[1]]
            offset = target - (start + len(code))
            assert -128 <= offset <= 127, f"branch to {b[1]} out of range"
            encoded.append(offset & 0xFF)
        else:
            encoded.append(b)
    out += encoded
    address += len(code)
    lines.append((start, encoded, comment, label))

pad = 0xFFFE - end
out += [0x00] * pad
out += [ORG & 0xFF, ORG >> 8]  # reset vector
assert len(out) == 64

import os, sys

root = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

listing = []
for start, encoded, comment, label in lines:
    hexes = " ".join(f"{b:02x}" for b in encoded)
    tag = f"{label}:" if label else ""
    listing.append(f"{start:04x}  {hexes:<10} {tag:<9}{comment}")
if pad:
    listing.append(f"{end:04x}  {' '.join(['00'] * pad):<10} {'':<9}(unused)")
listing.append(f"fffe  {ORG & 0xFF:02x} {ORG >> 8:02x}      {'':<9}reset vector: $FFC0")
listing.append(f"; {end - ORG} bytes of code, {pad} unused")

with open(os.path.join(root, "spc700-boot-rom.bin"), "wb") as f:
    f.write(bytes(out))
with open(os.path.join(root, "listing.txt"), "w") as f:
    f.write("\n".join(listing) + "\n")
with open(os.path.join(root, "spc700_boot_rom.h"), "w") as f:
    f.write("// SPDX-License-Identifier: GPL-3.0-or-later\n// Copyright (c) 2026 StackBlender LLC\n//\n")
    f.write("// The SPC700 boot ROM (64 bytes, mapped at $FFC0-$FFFF). Generated by src/assemble.py;\n")
    f.write("// see README.md and listing.txt.\n\n#pragma once\n\n")
    f.write("static const unsigned char spc700_boot_rom[64] = {\n")
    for i in range(0, 64, 8):
        f.write("\t" + ", ".join(f"0x{b:02x}" for b in out[i:i + 8]) + ",\n")
    f.write("};\n")
print("\n".join(listing))
